apiVersion: v1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: dev
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`your.example.com`) && PathPrefix(`/notls`)
    kind: Rule
    services:
    - name: whoami
      port: 80

---
apiVersion: v1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: dev
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`your.example.com`) && PathPrefix(`/tls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: myresolver
