apiVersion: v1/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: dev
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`your.example.com`) && PathPrefix(`/notls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
